namespace DuckType.Generator;

internal static class EmbeddedSources
{
    public const string Attributes = """
        // <auto-generated/>
        #nullable enable
        namespace DuckType
        {
            /// <summary>Marks an interface as a structural "shape" contract that other,
            /// unrelated types may satisfy without declaring or implementing it.</summary>
            [System.AttributeUsage(System.AttributeTargets.Interface)]
            public sealed class DuckShapeAttribute : System.Attribute
            {
            }

            /// <summary>Marks a method whose duck-typed parameter(s) accept any type that
            /// structurally matches the parameter's <see cref="DuckShapeAttribute"/> interface,
            /// resolved and dispatched at compile time via generated interceptors.</summary>
            [System.AttributeUsage(System.AttributeTargets.Method)]
            public sealed class DuckTypedAttribute : System.Attribute
            {
            }

            /// <summary>Thrown when a duck-typed call reaches the non-intercepted fallback path,
            /// which normally only happens if the argument's shape could not be verified at
            /// compile time (verified mismatches are reported as build errors instead).</summary>
            public sealed class DuckShapeMismatchException : System.Exception
            {
                public DuckShapeMismatchException(System.Type actualType, System.Type shapeType)
                    : base($"Type '{actualType}' does not structurally satisfy shape '{shapeType}'.")
                {
                }
            }
        }
        """;

    public const string InterceptsLocationAttributePolyfill = """
        // <auto-generated/>
        #pragma warning disable CS9113 // positional parameters are read by the compiler itself, not by this type
        namespace System.Runtime.CompilerServices
        {
            [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = true)]
            file sealed class InterceptsLocationAttribute(int version, string data) : System.Attribute
            {
            }
        }
        #pragma warning restore CS9113
        """;
}
